name: forlint

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
   lint:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: NOAA-GFDL/simple_lint@v3
           with:
             failure: true
             ftn_line_len: 101
