name: conda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
        with:
            submodules: recursive
            fetch-depth: 0  # https://github.com/pypa/setuptools_scm/issues/480
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies with pip in conda
        run: |
          python -m pip install --upgrade pip
          pip install -r test-time-requirements.txt
      - name: Install PyPartMC
        run: |
          pip install -e .
      - name: Test with pytest
        run: |
          cd tests
          pytest -v -s -We -p no:unraisableexception -k 'not test_todos_annotated' .
