name: urlcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 13 * * 4'

jobs:
  url-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: urlstechie/urlchecker-action@master
        with:
          file_types: .md,.py,.json,.ipynb,.yaml,.yml,.toml,.c,.hpp,.cpp,.F90,.f90,.txt,.dat,.cff
          print_all: false
          verbose: true
          timeout: 7
          retry_count: 3
          exclude_urls: https://www.gnu.org/licenses/gpl-3.0.en.html,https://www.gnu.org/licenses/gpl-3.0.html,https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
          exclude_patterns: http://purl.org,http://www.w3.org
          exclude_files: .github/workflows/urlcheck.yml
